apiVersion: batch/v1
kind: CronJob
metadata:
  name: clamav-rest-sigmon
spec:
  schedule: "0 0,12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: clamav-rest-sigmon
            image: docker.io/arizon/clamav-rest-sigmon:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 9001
              - containerPort: 8443
            envFrom:
              - configMapRef: 
                  name: clamav-rest
            env:
              - name: CLAMAV_REST_URL
                value: http://clamav-rest-service:9000
              - name: CRONJOB
                value: "true"
