apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-rest-sigmon
spec:
  replicas: 1
  selector:
    matchLabels:
      health: clamav-rest-sigmon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  template:
    metadata:
      labels:
        health: clamav-rest-sigmon
    spec:
      containers:
      - name: clamav-rest-sigmon
        restartPolicy: Always
        image: docker.io/arizon/clamav-rest-sigmon:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9001
          - containerPort: 8443
        envFrom:
          - configMapRef: 
              name: clamav-rest
        env:
          - name: CLAMAV_REST_URL
            value: http://clamav-rest-service:9000
