apiVersion: v1
kind: Service
metadata:
  name: clamav-rest-sigmon
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  - name: http
    port: 9001
    targetPort: 9001
  selector:
    app: clamav-rest-sigmon
  type: ClusterIP
